paths:
  json: generated/json
  yml: generated/server
panels:
  - component: SelectRoute
    label: Select a route
    value: select
  - component: GetApp
    label: Scaffold an entire directory structure using the current config
    value: getApp
  - component: RetrieveObjects
    label: Retrieve objects from noodl files
    value: retrieveObjects
  - component: RunServer
    label: Run server
    value: server
