org: pfftdammitchris
app: noodl-api
service: metadata
provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  region: us-west-1
  apiGateway:
    shouldStartNameWithService: true
plugins:
  - serverless-offline
functions:
  graphql:
    handler: dist/server.handler
    events:
      - http:
          path: graphql # define Lambda endpoint
          method: any # any HTTP method can access this Lambda
          cors: true # enable CORS
