import { YAMLNode } from '../types/internalTypes';
import * as seqUtil from './seq';
declare const Identify: {
    action: {
        any: (n: YAMLNode) => any;
        builtIn: (n: YAMLNode) => any;
        evalObject: (n: YAMLNode) => any;
        pageJump: (n: YAMLNode) => any;
        popUp: (n: YAMLNode) => any;
        popUpDismiss: (n: YAMLNode) => any;
        refresh: (n: YAMLNode) => any;
        saveObject: (n: YAMLNode) => any;
        updateObject: (n: YAMLNode) => any;
    };
    actionChain: typeof seqUtil.isActionChain;
    component: {
        any(v: unknown): boolean;
        button: (n: YAMLNode) => any;
        divider: (n: YAMLNode) => any;
        footer: (n: YAMLNode) => any;
        header: (n: YAMLNode) => any;
        image: (n: YAMLNode) => any;
        label: (n: YAMLNode) => any;
        list: (n: YAMLNode) => any;
        listItem: (n: YAMLNode) => any;
        plugin: (n: YAMLNode) => any;
        pluginHead: (n: YAMLNode) => any;
        pluginBodyTail: (n: YAMLNode) => any;
        popUp: (n: YAMLNode) => any;
        register: (n: YAMLNode) => any;
        select: (n: YAMLNode) => any;
        scrollView: (n: YAMLNode) => any;
        textField: (n: YAMLNode) => any;
        textView: (n: YAMLNode) => any;
        video: (n: YAMLNode) => any;
        view: (n: YAMLNode) => any;
    };
    boolean: (n: YAMLNode) => any;
    booleanTrue: (n: YAMLNode) => any;
    booleanFalse: (n: YAMLNode) => any;
    continue: (n: YAMLNode) => any;
    reference: (n: YAMLNode) => any;
    evalReference: (n: YAMLNode) => any;
    localReference: (n: YAMLNode) => any;
    rootReference: (n: YAMLNode) => any;
    traverseReference: (n: YAMLNode) => any;
    emit: (n: YAMLNode) => any;
    goto: (n: YAMLNode) => any;
    if: (n: YAMLNode) => any;
    init: (n: YAMLNode) => any;
    toast: (n: YAMLNode) => any;
};
export default Identify;
