import { YAMLMap } from 'yaml';
export declare function isActionLike(node: YAMLMap): boolean;
export declare function isBuiltInAction(node: YAMLMap): boolean;
export declare function isEvalObjectAction(node: YAMLMap): boolean;
export declare function isPageJumpAction(node: YAMLMap): boolean;
export declare function isPopUpAction(node: YAMLMap): boolean;
export declare function isPopUpDismissAction(node: YAMLMap): boolean;
export declare function isRefreshAction(node: YAMLMap): boolean;
export declare function isSaveObjectAction(node: YAMLMap): boolean;
export declare function isUpdateObjectAction(node: YAMLMap): boolean;
export declare function isComponentLike(node: YAMLMap): boolean;
export declare const isComponent: (node: YAMLMap) => boolean;
export declare function isButtonComponent(node: YAMLMap): boolean;
export declare function isDividerComponent(node: YAMLMap): boolean;
export declare function isFooterComponent(node: YAMLMap): boolean;
export declare function isHeaderComponent(node: YAMLMap): boolean;
export declare function isImageComponent(node: YAMLMap): boolean;
export declare function isLabelComponent(node: YAMLMap): boolean;
export declare function isListComponent(node: YAMLMap): boolean;
export declare function isListItemComponent(node: YAMLMap): boolean;
export declare function isPluginComponent(node: YAMLMap): boolean;
export declare function isPluginHeadComponent(node: YAMLMap): boolean;
export declare function isPluginBodyTailComponent(node: YAMLMap): boolean;
export declare function isPopUpComponent(node: YAMLMap): boolean;
export declare function isRegisterComponent(node: YAMLMap): boolean;
export declare function isSelectComponent(node: YAMLMap): boolean;
export declare function isScrollViewComponent(node: YAMLMap): boolean;
export declare function isTextFieldComponent(node: YAMLMap): boolean;
export declare function isTextViewComponent(node: YAMLMap): boolean;
export declare function isVideoComponent(node: YAMLMap): boolean;
export declare function isViewComponent(node: YAMLMap): boolean;
export declare function hasActionTypeEqualTo(node: YAMLMap, value: string): boolean;
export declare function hasComponentTypeEqualTo(node: YAMLMap, value: string): boolean;
export declare function isEmitObject(node: YAMLMap): boolean;
export declare function isGotoObject(node: YAMLMap): boolean;
export declare function isIfObject(node: YAMLMap): boolean;
export declare function isInitObject(node: YAMLMap): boolean;
export declare function isToastObject(node: YAMLMap): boolean;
