import { Scalar } from 'yaml';
export declare function getScalarValue(node: any): any;
export declare function isBoolean(node: any): boolean;
export declare function isBooleanTrue(node: any): boolean;
export declare function isBooleanFalse(node: any): boolean;
export declare function isContinue(node: Scalar): boolean;
export declare function isNumber(node: Scalar): boolean;
export declare function isString(node: Scalar): boolean;
export declare function isReference(node: Scalar): boolean;
export declare function isLocalReference(node: Scalar): boolean;
export declare function isRootReference(node: Scalar): boolean;
export declare function isEvalReference(node: string | Scalar): boolean;
export declare function isTraverseReference(node: string | Scalar): boolean;
export declare function startsWith(value: string | undefined, node: Scalar): boolean;
export declare function endsWith(value: string | undefined, node: Scalar): boolean;
export declare function getPreparedKeyForDereference(node: string | Scalar): string | false;
