export type ActionType =
	| 'builtIn'
	| 'evalObject'
	| 'pageJump'
	| 'popUp'
	| 'popUpDismiss'
	| 'refresh'
	| 'saveObject'
	| 'updateObject'

export type ComponentType =
	| 'button'
	| 'divider'
	| 'footer'
	| 'header'
	| 'image'
	| 'label'
	| 'list'
	| 'listItem'
	| 'page'
	| 'plugin'
	| 'pluginHead'
	| 'pluginBodyTail'
	| 'popUp'
	| 'register'
	| 'select'
	| 'scrollView'
	| 'textField'
	| 'textView'
	| 'video'
	| 'view'

export type ContentType =
	| 'countryCode'
	| 'email'
	| 'formattedDate'
	| 'formattedDuration'
	| 'listObject'
	| 'number'
	| 'password'
	| 'passwordHidden'
	| 'phoneNumber'
	| 'phone'
	| 'tel'
	| 'text'
	| 'videoSubStream'
	| 'vidoeSubStream'

export type EventType =
	| 'onClick'
	| 'onChange'
	| 'onHover'
	| 'onMouseEnter'
	| 'onMouseLeave'
	| 'onMouseOut'
	| 'onMouseOver'
