export declare const action: {
    readonly BUILTIN: "builtIn";
    readonly EVALOBJECT: "evalObject";
    readonly OPENCAMERA: "openCamera";
    readonly OPENPHOTOLIBRARY: "openPhotoLibrary";
    readonly OPENDOCUMENTMANAGER: "openDocumentManager";
    readonly PAGEJUMP: "pageJump";
    readonly POPUP: "popUp";
    readonly POPUPDISMISS: "popUpDismiss";
    readonly REFRESH: "refresh";
    readonly REGISTER: "register";
    readonly REMOVESIGNATURE: "removeSignature";
    readonly SAVEOBJECT: "saveObject";
    readonly SAVESIGNATURE: "saveSignature";
    readonly UPDATEOBJECT: "updateObject";
};
export declare const actionTypes: ("builtIn" | "evalObject" | "pageJump" | "popUp" | "popUpDismiss" | "refresh" | "saveObject" | "updateObject" | "register" | "openCamera" | "openPhotoLibrary" | "openDocumentManager" | "removeSignature" | "saveSignature")[];
export declare const component: {
    readonly BUTTON: "button";
    readonly CANVAS: "canvas";
    readonly CHART: "chart";
    readonly CHATLIST: "chatList";
    readonly ECOSDOC: "ecosDoc";
    readonly DIVIDER: "divider";
    readonly FOOTER: "footer";
    readonly HEADER: "header";
    readonly IMAGE: "image";
    readonly LABEL: "label";
    readonly LIST: "list";
    readonly LISTITEM: "listItem";
    readonly MAP: "map";
    readonly PAGE: "page";
    readonly PLUGIN: "plugin";
    readonly PLUGINHEAD: "pluginHead";
    readonly PLUGINBODYTAIL: "pluginBodyTail";
    readonly POPUP: "popUp";
    readonly REGISTER: "register";
    readonly SELECT: "select";
    readonly SCROLLVIEW: "scrollView";
    readonly TEXTFIELD: "textField";
    readonly TEXTVIEW: "textView";
    readonly VIDEO: "video";
    readonly VIEW: "view";
};
export declare const componentKeys: readonly ["backgroundColor", "borderRadius", "chatItem", "children", "contentType", "dataId", "dataIn", "dataKey", "dataModel", "ecosObj", "height", "isEditable", "itemObject", "iteratorVar", "itmeObject", "listObject", "onChange", "onClick", "onInput", "optionKey", "options", "path", "pathSelected", "placeHolder", "placeholder", "refresh", "required", "style", "text", "text=func", "textAlign", "textBoard", "type", "viewTag", "width", "zIndex", "chatItem"];
export declare const componentTypes: ("map" | "page" | "image" | "video" | "list" | "popUp" | "button" | "canvas" | "chart" | "chatList" | "ecosDoc" | "divider" | "footer" | "header" | "label" | "listItem" | "plugin" | "pluginHead" | "pluginBodyTail" | "register" | "select" | "scrollView" | "textField" | "textView" | "view")[];
export declare const contentTypes: readonly ["countryCode", "email", "file", "formattedDate", "formattedDuration", "hidden", "listObject", "messageHidden", "number", "password", "passwordHidden", "phone", "phoneNumber", "tel", "text", "timer", "videoSubStream"];
export declare const deviceTypes: readonly ["web", "ios", "android"];
export declare const styleKeys: readonly ["FontSize", "axis", "background", "backgroundColor", "border", "borderColor", "borderRadius", "borderRaduis", "borderWidth", "boxShadow", "boxSizing", "color", "contentSize", "diaplay", "display", "filter", "float", "flex", "flexFlow", "fontColor", "fontFamily", "fontSize", "fontStyle", "fontWeight", "foontWeight", "height", "hieght", "isHidden", "justifyContent", "left", "letterSpacing", "lineHeight", "marginLeft", "marginTop", "onClick", "padding", "paddingBottom", "paddingLeft", "placeholder", "position", "required", "shadow", "text-align", "textAlign", "textDecoration", "textIndent", "top", "width", "zIndex"];
export declare const userEvent: readonly ["onBlur", "onClick", "onChange", "onFocus", "onHover", "onInput", "onMouseEnter", "onMouseLeave", "onMouseOut", "onMouseOver"];
