export const action = {
	BUILTIN: 'builtIn',
	EVALOBJECT: 'evalObject',
	PAGEJUMP: 'pageJump',
	POPUP: 'popUp',
	POPUPDISMISS: 'popUpDismiss',
	REFRESH: 'refresh',
	REGISTER: 'register',
	SAVEOBJECT: 'saveObject',
	UPDATEOBJECT: 'updateObject',
} as const

export const actionTypes = Object.values(action)

export const component = {
	BUTTON: 'button',
	CHART: 'chart',
	CHATLIST: 'chatList',
	DIVIDER: 'divider',
	FOOTER: 'footer',
	HEADER: 'header',
	IMAGE: 'image',
	LABEL: 'label',
	LIST: 'list',
	LISTITEM: 'listItem',
	PAGE: 'page',
	PLUGIN: 'plugin',
	PLUGINHEAD: 'pluginHead',
	PLUGINBODYTAIL: 'pluginBodyTail',
	POPUP: 'popUp',
	REGISTER: 'register',
	SELECT: 'select',
	SCROLLVIEW: 'scrollView',
	TEXTFIELD: 'textField',
	TEXTVIEW: 'textView',
	VIDEO: 'video',
	VIEW: 'view',
} as const

export const componentKeys = [
	'backgroundColor',
	'borderRadius',
	'chatItem',
	'children',
	'contentType',
	'dataId',
	'dataKey',
	'dataModel',
	'height',
	'isEditable',
	'itemObject',
	'iteratorVar',
	'itmeObject',
	'listObject',
	'onChange',
	'onClick',
	'optionKey',
	'options',
	'path',
	'pathSelected',
	'placeHolder',
	'placeholder',
	'refresh',
	'required',
	'style',
	'text',
	'text=func',
	'textAlign',
	'textBoard',
	'type',
	'viewTag',
	'width',
	'zIndex',
	'chatItem',
] as const

export const componentTypes = Object.values(component)

export const contentTypes = [
	'countryCode',
	'email',
	'file',
	'formattedDate',
	'formattedDuration',
	'hidden',
	'listObject',
	'messageHidden',
	'number',
	'password',
	'passwordHidden',
	'phone',
	'phoneNumber',
	'tel',
	'text',
	'timer',
	'videoSubStream',
	'vidoeSubStream',
] as const

export const styleKeys = [
	'FontSize',
	'axis',
	'background',
	'backgroundColor',
	'border',
	'borderColor',
	'borderRadius',
	'borderRaduis',
	'borderWidth',
	'boxShadow',
	'boxSizing',
	'color',
	'contentSize',
	'diaplay',
	'display',
	'filter',
	'flex',
	'flexFlow',
	'fontColor',
	'fontFamily',
	'fontSize',
	'fontStyle',
	'fontWeight',
	'foontWeight',
	'height',
	'hieght',
	'isHidden',
	'justifyContent',
	'left',
	'letterSpacing',
	'lineHeight',
	'marginLeft',
	'marginTop',
	'onClick',
	'padding',
	'paddingBottom',
	'paddingLeft',
	'placeholder',
	'position',
	'required',
	'shadow',
	'text-align',
	'textAlign',
	'textDecoration',
	'textIndent',
	'top',
	'width',
	'zIndex',
] as const

export const userEvent = [
	'onBlur',
	'onClick',
	'onChange',
	'onFocus',
	'onHover',
	'onMouseEnter',
	'onMouseLeave',
	'onMouseOut',
	'onMouseOver',
] as const
