[build]
  command = "npm install && npm run build"
  publish = "functions"
  functions = "functions"

[dev]
  src = "src/functions"
  functionsPort = 3001
  autoLaunch = false
  port = 3000

[functions]
  directory = "src/functions"

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"