[build]
  command = "npm run build"
  functions = "functions"

[dev]
  port = 3001

[functions]
  directory = 'functions'
  node_bundler = 'esbuild'

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"