[build]
  command = "npm install && npm run build"
  publish = "functions"
  functions = "functions"

[dev]
  functions = "src"
  functionsPort = 3001
  autoLaunch = false
  port = 3000

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"