"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RETRIEVE_NOODL_OBJECTS_WITH_KEYS = exports.RETRIEVE_NOODL_PROPERTIES = exports.RETRIEVE_NOODL_OBJECTS_YML = exports.RETRIEVE_NOODL_OBJECTS_JSON = void 0;
exports.RETRIEVE_NOODL_OBJECTS_JSON = 'RETRIEVE_NOODL_OBJECTS_JSON';
exports.RETRIEVE_NOODL_OBJECTS_YML = 'RETRIEVE_NOODL_OBJECTS_YML';
exports.RETRIEVE_NOODL_PROPERTIES = 'RETRIEVE_NOODL_PROPERTIES';
exports.RETRIEVE_NOODL_OBJECTS_WITH_KEYS = 'RETRIEVE_NOODL_OBJECTS_WITH_KEYS';
//# sourceMappingURL=constants.js.map