export const RETRIEVE_NOODL_OBJECTS_JSON = 'RETRIEVE_NOODL_OBJECTS_JSON'
export const RETRIEVE_NOODL_OBJECTS_YML = 'RETRIEVE_NOODL_OBJECTS_YML'
export const RETRIEVE_NOODL_PROPERTIES = 'RETRIEVE_NOODL_PROPERTIES'
export const RETRIEVE_NOODL_OBJECTS_WITH_KEYS =
	'RETRIEVE_NOODL_OBJECTS_WITH_KEYS'
